package com.oa.hibernate.beans;

import java.util.Date;

/**
 * AbstractOff generated by MyEclipse Persistence Tools
 */

public abstract class AbstractOff implements java.io.Serializable {

	// Fields

	private Long id;
	private String username;
	private Date begin;
	private Date end;
	private String reson;
	private Long status;
	private String realname;

	// Constructors

	/** default constructor */
	public AbstractOff() {
	}

	/** full constructor */
	public AbstractOff(String username, Date begin, Date end, String reson,
			Long status,String realname) {
		this.username = username;
		this.begin = begin;
		this.end = end;
		this.reson = reson;
		this.status = status;
		this.realname=realname;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public String getReson() {
		return this.reson;
	}

	public void setReson(String reson) {
		this.reson = reson;
	}

	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

}