package com.oa.hibernate.beans;
// default package


/**
 * AbstractRegime generated by MyEclipse Persistence Tools
 */

public abstract class AbstractRegime  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String content;


    // Constructors

    /** default constructor */
    public AbstractRegime() {
    }

    
    /** full constructor */
    public AbstractRegime(String content) {
        this.content = content;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
   








}