package com.oa.hibernate.beans;

import java.util.Date;

/**
 * AbstractAttendance generated by MyEclipse Persistence Tools
 */

public abstract class AbstractAttendance implements java.io.Serializable {

	// Fields

	private Long id;
	private String username;
	private Date ontime;
	private Date offtime;
	private String onresult;
	private String offresult;

	// Constructors

	/** default constructor */
	public AbstractAttendance() {
	}

	/** minimal constructor */
	public AbstractAttendance(String username) {
		this.username = username;
	}

	/** full constructor */
	public AbstractAttendance(String username, Date ontime, Date offtime,String onresult,String offresult) {
		this.username = username;
		this.ontime = ontime;
		this.offtime = offtime;
		this.onresult=onresult;
		this.offresult=offresult;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getOntime() {
		return this.ontime;
	}

	public void setOntime(Date ontime) {
		this.ontime = ontime;
	}

	public Date getOfftime() {
		return this.offtime;
	}

	public void setOfftime(Date offtime) {
		this.offtime = offtime;
	}

	public String getOnresult() {
		return onresult;
	}

	public void setOnresult(String onresult) {
		this.onresult = onresult;
	}

	public String getOffresult() {
		return offresult;
	}

	public void setOffresult(String offresult) {
		this.offresult = offresult;
	}

}