package com.oa.hibernate.beans;

/**
 * AbstractStaff generated by MyEclipse Persistence Tools
 */

public abstract class AbstractStaff implements java.io.Serializable {

	// Fields

	private Long userid;
	private String username;
	private String realname;
	private String password;
	private String department;
	private Long mobile;
	private String email;
	private Long power;
	private String pozition;
	private String address;

	// Constructors

	/** default constructor */
	public AbstractStaff() {
	}

	/** minimal constructor */
	public AbstractStaff(String username, String realname, String password,
			String department, Long power, String pozition) {
		this.username = username;
		this.realname = realname;
		this.password = password;
		this.department = department;
		this.power = power;
		this.pozition = pozition;
	}

	/** full constructor */
	public AbstractStaff(String username, String realname, String password,
			String department, Long mobile, String email, Long power,
			String pozition,String address) {
		this.username = username;
		this.realname = realname;
		this.password = password;
		this.department = department;
		this.mobile = mobile;
		this.email = email;
		this.power = power;
		this.pozition = pozition;
	}

	// Property accessors

	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public Long getMobile() {
		return this.mobile;
	}

	public void setMobile(Long mobile) {
		this.mobile = mobile;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Long getPower() {
		return this.power;
	}

	public void setPower(Long power) {
		this.power = power;
	}

	public String getPozition() {
		return this.pozition;
	}

	public void setPozition(String pozition) {
		this.pozition = pozition;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}