package com.oa.hibernate.beans;

import java.util.Date;

/**
 * AbstractMeeting generated by MyEclipse Persistence Tools
 */

public abstract class AbstractMeeting implements java.io.Serializable {

	// Fields

	private Long id;
	private String room;
	private Date begintime;
	private Date endtime;
	private String attendant;
	private String content;

	// Constructors

	/** default constructor */
	public AbstractMeeting() {
	}

	/** full constructor */
	public AbstractMeeting(String room, Date begintime, Date endtime,
			String attendant,String content) {
		this.room = room;
		this.begintime = begintime;
		this.endtime = endtime;
		this.attendant = attendant;
		this.content=content;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public Date getBegintime() {
		return this.begintime;
	}

	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getAttendant() {
		return this.attendant;
	}

	public void setAttendant(String attendant) {
		this.attendant = attendant;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}