package com.oa.hibernate.beans;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Attendance generated by MyEclipse Persistence Tools
 */
public class Attendance extends AbstractAttendance implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public Attendance() {
	}

	/** minimal constructor */
	public Attendance(String username) {
		super(username);
	}

	/** full constructor */
	public Attendance(String username, Date ontime, Date offtime,String onresult,String offresult) {
		super(username, ontime, offtime,onresult,offresult);
	}

}
