package com.oa.hibernate.beans;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Mail generated by MyEclipse Persistence Tools
 */
public class Mail extends AbstractMail implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Mail() {
	}

	/** minimal constructor */
	public Mail(String sender, String addressee, String title, Date sendtime,
			Long status) {
		super(sender, addressee, title, sendtime, status);
	}

	/** full constructor */
	public Mail(String sender, String addressee, String title, String content,
			Date sendtime, Long status) {
		super(sender, addressee, title, content, sendtime, status);
	}

}
