package com.oa.hibernate.beans;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Meeting generated by MyEclipse Persistence Tools
 */
public class Meeting extends AbstractMeeting implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Meeting() {
	}

	/** full constructor */
	public Meeting(String room, Date begintime, Date endtime, String attendant,String content) {
		super(room, begintime, endtime, attendant,content);
	}

}
