package com.oa.hibernate.beans;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * News generated by MyEclipse Persistence Tools
 */
public class News extends AbstractNews implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public News() {
	}

	/** full constructor */
	public News(String content, Date newsdate) {
		super(content, newsdate);
	}

}
