package com.oa.hibernate.beans;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * Off generated by MyEclipse Persistence Tools
 */
public class Off extends AbstractOff implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Off() {
	}

	/** full constructor */
	public Off(String username, Date begin, Date end, String reson, Long status,String realname) {
		super(username, begin, end, reson, status,realname);
	}

}
