package com.oa.hibernate.beans;
// default package
// Generated by MyEclipse Persistence Tools

import java.util.Date;



/**
 * Regime generated by MyEclipse Persistence Tools
 */
public class Regime extends AbstractRegime implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Regime() {
    }

    
    /** full constructor */
    public Regime(String content) {
        super(content);        
    }
   
}
