package com.oa.hibernate.beans;

// Generated by MyEclipse Persistence Tools

/**
 * Staff generated by MyEclipse Persistence Tools
 */
public class Staff extends AbstractStaff implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public Staff() {
	}

	/** minimal constructor */
	public Staff(String username, String realname, String password,
			String department, Long power, String pozition) {
		super(username, realname, password, department, power, pozition);
	}

	/** full constructor */
	public Staff(String username, String realname, String password,
			String department, Long mobile, String email, Long power,
			String pozition,String address) {
		super(username, realname, password, department, mobile, email, power,
				pozition,address);
	}

}
